# Generated by Django 4.2.3 on 2023-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
